### PR TITLE
Updated popover docs to show onToggle

### PR DESCRIPTION
**Pull request by DigiNanigans**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests
- [ ] Other

# Why is it needed?

Documented existing `onChange$` functionality on the `<Popover.Panel>` component that allows a user to track the current state of the popover.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have ran `pnpm change` and documented my changes
- [x] I have add necessary docs (if needed)
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by DigiNanigans** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by DigiNanigans** [comment]
recheck

**Comment by thejackshelton** [comment]
Looks great! Regarding the CLA sign, I think the problem is you committed under a different github account. If you could comment on that account that should work and I'd be happy to merge 👍

**Comment by DigiNanigans** [comment]
> Looks great! Regarding the CLA sign, I think the problem is you committed under a different github account. If you could comment on that account that should work and I'd be happy to merge 👍

Hmm, that account shouldn't have been involved with the commit. Let me look into it.

**Comment by DigiNanigans** [comment]
Should be all set now.

**Comment by thejackshelton** [comment]
LGTM! Merging

**Pull request merged**
