### PR TITLE
fix(nx preview): fix pagination PR #492 that broke preview

### PR DESCRIPTION
**Pull request by maiieul**
# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests

# Description

PR #492 broke docs preview. This PR fixes the issue without improving the docs. I simply commented out the old Pagination components for the time being since they have been changed.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by gioboa — COMMENTED** [review]
I think we can remove _index.tsx too

**Comment by maiieul** [comment]
@gioboa I removed the _index for the headless route but kept the one for fluffy as otherwise the page would return a 404 not found.

**Comment by gioboa** [comment]
Thanks @maiieul you rock

**Comment by thejackshelton** [comment]
Awesome stuff! Merging

**Pull request merged**
