### PR TITLE
fix(dialog): ESC freezes browser

### PR DESCRIPTION
**Pull request by PatrickJS**
# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests
- [ ] Other

# Why is it needed?
when you press Enter then ESC the dialog will be out of sync with the signal

### CODE REVIEW

**Comment by thejackshelton** [comment]
Not sure I understand @PatrickJS, isn't the exact code already here?

```tsx
    const escapeKeyListener = overrideNativeDialogEscapeBehaviorWith(() => {
      showSig.value = false;
    });

    window.addEventListener('keydown', escapeKeyListener);
```

**Comment by thejackshelton** [comment]
Is `showSig.value` not firing there? If so, let's refactor out `overrideNativeDialogEscapeBehaviorWith` entirely and use a sync$ to preventDefault, then keep the code here in this PR.

If you could add that commit.

**Comment by PatrickJS** [comment]
@thejackshelton yeah the event fires from dialog and closes the modal then freezes the browser

**Comment by PatrickJS** [comment]
@thejackshelton feel free to edit the code in the PR

**Pull request merged**
