### PR TITLE
WIP 253 add carousel component

### PR DESCRIPTION
**Pull request by tleperou**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

* expose the state outside of the Root
* add support to multiple visible item per page
* add netflix example
* shorten the public api

# Use cases and why

Anywhere users want to use Carousel to display several items.

# Screenshots/Demo

image

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
Thanks for your help. I tested the carousel and with Chrome I have this strange effect
https://www.loom.com/share/3b0d4367cbba4b7e8984510cc60a1301
🤔

**Comment by tleperou** [comment]
I improved the example. And couldn't reproduce the same behaviour.

Could you confirm your still that bahviour?

(tested on Chrome and Arc at the moment)

🙌

**Comment by gioboa** [comment]
> I improved the example. And couldn't reproduce the same behaviour.
> 
> Could you confirm your still that bahviour?
> 
> (tested on Chrome and Arc at the moment)
> 
> 🙌

I still have some weird flaws 🤔

**Comment by tleperou** [comment]
Could you take a screen record with your mouse and keyboard indicators on ? (I think there's this option in the screen recorder)

**Comment by shairez** [comment]
based on #258 ... can we close this one @tleperou ? is it the same work?

**Comment by tleperou** [comment]
this one brings some improvements about
- the abstraction with the feature / styles
- the support of the auto (one or many slides per view)
- the overall accessibility level

It shall be for tested again since @gioboa found out weird behaviour with the auto mode (that I couldn't reproduce)

**Comment by shairez** [comment]
thanks @tleperou 

@gioboa can you please merge this during you and @itaim18 's session?

**Comment by gioboa** [comment]
> thanks @tleperou
> 
> @gioboa can you please merge this during you and @itaim18 's session?

Yep sure

**Pull request merged**
