### PR TITLE
I have read the CLA Document and I hereby sign the CLA

### PR DESCRIPTION
**Pull request by JerryWu1234**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests
- [ ] Other

# Why is it needed?

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have ran `pnpm change` and documented my changes
- [ ] I have add necessary docs (if needed)
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by JerryWu1234** [comment]
> I have read the CLA Document and I hereby sign the CLA

I have read the CLA Document and I hereby sign the CLA

**Comment by JerryWu1234** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by maiieul — CHANGES_REQUESTED** [review]
Oh oh.. I think you did `pnpm change` and marked it as a major release 😱.. Please could you remove that file from your local PR branch, commit and push again?

**Comment by thejackshelton** [comment]
How about let's make a new PR actually

**Comment by thejackshelton** [comment]
@JerryWu1234 let's make a new pr with a random comment somewhere. You don't need to run `pnpm change`

**Pull request closed without merging**
