### PR TITLE
docs(readme.md): aligned the components status with the website

### LINKED ISSUE #504: bug: available components in readme
The readme file seems to be unaligned with the real status of the components availability

### PR DESCRIPTION
**Pull request by ilteoood**
aligned the components status with the website, added the pagination and separator components

fix #504

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

fix: readme

# Use cases and why

Readme was unaligned

# Screenshots/Demo

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by ilteoood** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ilteoood** [comment]
recheck

**Review by gioboa — APPROVED** [review]
LGTM

**Comment by gioboa** [comment]
@all-contributors please add @ilteoood for docs, maintenance

**Comment by gioboa** [comment]
@all-contributors please add @ilteoood for docs, maintenance

**Pull request merged**
