### PR TITLE
fix(headless/combobox): fix dark mode and add basic a11y tests

### LINKED ISSUE #661: Dark mode styling broke on the docs site for combobox
On the docs site, when using a dark theme on the system, the ComboBox options are dark even though the page theme is light

image

In dark mode, the text color is still set to light mode which makes the test unreadable. 

image

@shairez , we may be able to use our accessibility tests ([color-contrast](https://dequeuniversity.com/rules/axe/4.4/color-contrast)) to ensure that theming issues like this don't occur.

I'll work on a fix for this

### PR DESCRIPTION
**Pull request by cwoolum**
# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [x] Docs / tests
- [ ] Other

# Why is it needed?

Fixes #661 

Here is the updated UX with dark mode configured

image

Light mode is fixed as well

image

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have ran `pnpm change` and documented my changes
- [x] I have add necessary docs (if needed)
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by cwoolum** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thejackshelton** [comment]
Looks great @cwoolum! Is the PR ready for merge?

**Comment by cwoolum** [comment]
Yes, I'm good!

**Comment by thejackshelton** [comment]
Merged!

**Pull request merged**
