### PR TITLE
fix(repo): various target and dependency updates

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests

# Description
- Fixed an issue with Nx not resolving dependencies between projects. This allowed to remove the workaround with statements like`"@qwik-ui/utils": "workspace:*"` in `package.json`s
- Fixed storybook for headless project
- Removed duplicated storybook dependencies with wrong versions from `@qwik-ui/fluffy`
- Fixed wrong paths used for the utils library

# Use cases and why

# Screenshots/Demo

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by gioboa** [comment]
Thanks @fabiobiondi you rock 😊

**Comment by dmitry-stepanenko** [comment]
Hey @gioboal I also wanna test one thing tomorrow, will mark it as ready to review right after that 🙂

**Review by PatrickJS — APPROVED** [review]

**Review by gioboa — APPROVED** [review]
It looks good, I don't know why we had the deps in the inner package.json

**Comment by thejackshelton** [comment]
LGTM!

**Pull request merged**
