### PR TITLE
Alt headless select implementation

### PR DESCRIPTION
**Pull request by shiroinegai**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

This is an alternate implementation for headless Select with a demo which includes some minimal styling.

This implementation largely draws from [Radix UI's usage model](https://www.radix-ui.com/docs/primitives/components/select) as well as [Open UI's selectmenu prototype](https://open-ui.org/prototypes/selectmenu).

# Screenshots/Demo

Demo is added to `/headless/select/` path, viewable after running `npx nx start website`.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by shiroinegai** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shairez** [comment]
thanks @shiroinegai !

Can I merge this PR? or do you still work on it? 
(BTW, there are a couple of conflicts to resolve before it can be merged)

**Comment by shiroinegai** [comment]
I'm still actively working on it (right now, actually!). Is this implementation going to replace the existing Select? If so, I'll be renaming the export and put it into the new documentation page.

**Comment by shiroinegai** [comment]
Hey @shairez , I think I have resolved the conflicts and this current commit is in the exact same state as you saw from yesterday's meeting. I'm still trying to implement the rest of the necessary behaviour but you can merge this PR for now.

**Comment by gioboa** [comment]
great work @shiroinegai 👏 
can you add the docs example in the daisy folder -> qwik-ui/packages/website/src/routes/docs/daisy/... please?

**Comment by shiroinegai** [comment]
Will do!

**Review by gioboa — APPROVED** [review]
Thanks, it looks good 😊

**Pull request merged**
