### PR TITLE
chore(contributing.md): add instructions for a basic dev workflow

### PR DESCRIPTION
**Pull request by voluntadpear**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

As part of `CONTRIBUTING.md` I think it's useful to have basic instructions on how to get a dev workflow running.

I couldn't find any instructions for this so after exploring a bit came up with what seems to me is the intended workflow.

Please let me know if you have an alternative preferred way of working and I can reflect that in the docs.

# Use cases and why

- 1. One use case
- 2. Another use case

# Screenshots/Demo

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by voluntadpear** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gilf** [comment]
Thanks for the contribution. Please see the comment I added

**Comment by voluntadpear** [comment]
@gilf Sorry, I can't find your comment. Could you point me to it please?

**Comment by gilf** [comment]
You can find it in the review:
"Storybook has hot reload wired, so no need to refresh the tab to see the change." 
Once you solve the comment we will be able to continue with the PR process.

**Comment by voluntadpear** [comment]
@gilf Thank you! I've updated the description based on Storybook having hot reloading enabled. Would you mind taking another look at this PR?

**Comment by reemardelarosa** [comment]
@voluntadpear can we include the scripts in package.json?

**Comment by voluntadpear** [comment]
@reemardelarosa I can do so. I'm not sure if the core devs prefer to push for using the NX cli as much as possible though. 

I can add the following scripts to the root `package.json`:

```
"dev": "npm run dev --workspace=packages/core",
"storybook": "npx nx storybook core",
```

and then update the docs accordingly.

Thoughts @gilf?

**Comment by shairez** [comment]
sounds good @voluntadpear !
Thanks for the suggestion @reemardelarosa

**Comment by gilf** [comment]
> @voluntadpear can we include the scripts in package.json?

We are using nx as a monorepo management tool and therefore you should use nx CLI in order to run the scripts. Either run 
`nx run core:storybook`
or 
`nx storybook core`

**Comment by gilf** [comment]
> @reemardelarosa I can do so. I'm not sure if the core devs prefer to push for using the NX cli as much as possible though.
> 
> I can add the following scripts to the root `package.json`:
> 
> ```
> "dev": "npm run dev --workspace=packages/core",
> "storybook": "npx nx storybook core",
> ```
> 
> and then update the docs accordingly.
> 
> Thoughts @gilf?

Please don't. We use nx for all the CLI commands so look at the comment I wrote to @voluntadpear

**Pull request merged**
