### PR TITLE
fix(global.css): set background-color to header

### PR DESCRIPTION
**Pull request by wahyufeb**
# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests

# Description

Set the background color to the header based on the selected theme.

# Use cases and why

- 1. The header has no background yet

# Screenshots/Demo

Screen Shot 2023-02-23 at 8 13 49 AM

Screen Shot 2023-02-23 at 8 14 11 AM

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by wahyufeb** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by wahyufeb** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gioboa** [comment]
Looks good to me. 
You need to comment with:  `I have read the CLA Document and I hereby sign the CLA` to accept the CLA. Thanks

**Comment by gioboa** [comment]
This PR closes #185

**Comment by wahyufeb** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by wahyufeb** [comment]
> This PR closes #185

Okay, Thank you.

**Comment by gioboa** [comment]
Can you accept the CLA also with this user @wahyu Febrianto? the CI is complaining about it

**Comment by wahyufeb** [comment]
> Can you also accept the CLA with this user @wahyu Febrianto? the CI is complaining about it

I don't know about @wahyu Febrianto user, and it doesn't me.
Do you know how to remove it?

**Comment by gioboa** [comment]
CLA Assistant recognised a wrong user 🤷‍♂️ let's move on anyway

**Comment by gioboa** [comment]
@all-contributors please add @wahyufeb for code, bug

**Pull request merged**
