### PR TITLE
feat: update vite.config.ts

### PR DESCRIPTION
**Pull request by JerryWu1234**
fix: modify right base url

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests
- [ ] Other

# Why is it needed?

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have ran `pnpm change` and documented my changes
- [ ] I have add necessary docs (if needed)
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by gioboa — APPROVED** [review]
Nice :clap: @JerryWu1234

**Comment by JerryWu1234** [comment]
@gioboa Who can merge this PR?
Because my search doc PR needs this PR's code

**Review by gioboa — APPROVED** [review]

**Comment by gioboa** [comment]
> Nice 👏 @JerryWu1234

✅ Done

**Comment by JerryWu1234** [comment]
> > Nice 👏 @JerryWu1234
> 
> ✅ Done

when will we release a new version?

**Comment by gioboa** [comment]
> when will we release a new version?

Let's talk about this new version in the Qwik UI Discord server. Thanks

**Pull request merged**
