### PR TITLE
Checkbox

### PR DESCRIPTION
**Pull request by rossellamascia**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Created a base checkout component

https://github.com/qwikifiers/qwik-ui/issues/128 - Add Checkbox component

# Screenshots/Demo

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by rossellamascia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gioboa** [comment]
This PR will close #135

**Comment by rossellamascia** [comment]
@gioboa this PR does not close the 135 but the 128, or am I wrong?

**Comment by gioboa** [comment]
> @gioboa this PR does not close the 135 but the 128, or am I wrong?

Thanks, fixed 👍

**Comment by rossellamascia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rossellamascia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rossellamascia** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Rossella-Mascia-Neosyn** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gioboa** [comment]
@all-contributors please add @rossellamascia for code

**Pull request merged**
