### PR TITLE
fix(auto-imports): remove pnpm workspaces to re-enable vscode auto-imports

### PR DESCRIPTION
**Pull request by maiieul**
# What is it?

- [ ] Feature / enhancement
- [x] Bug
- [ ] Docs / tests

# Description

Seems that using pnpm workspaces inside of nx is causing issues with vscode auto-imports. Perhaps @dmitry-stepanenko could confirm?

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by maiieul** [comment]
Looks like tailwind:lint is failing because of that change :thinking:

**Comment by shairez** [comment]
This is not complete as we need to 

1. Move all of the dependencies inside of each project's package.json into the root package.json
2. Verify that all of the packages are being built correctly (also the website)
3. Find an automatic script that will allow us to sync the packages inside of each project with the root version numbers

**Comment by maiieul** [comment]
Hmmm I see.

I'm not sure I'd be very productive at finding the script for maintaining package versions. 

Although the design kits don't need package versioning since it's copy&paste, and we wouldn't need to have @qwik-ui/utils if we used the cva & clsx libraries (so no package versioning here either). 

For me only headless is necessary as a versioned package as of now. If you can agree with me to use the cva & clsx libraries, then it simplifies the problem. https://discord.com/channels/990511757091033108/1144897805903724564/1184777208187867136

**Comment by maiieul** [comment]
So I managed to "fix" this by removing old tailwind-kit code.

This is a good step towards a clean repo.

I'd say let's merge this and figure out later the script for package versioning.

(fluffy button is the same as the other PR I just opened, used it in here so that preview wouldn't complain about type errors)

**Comment by maiieul** [comment]
Ups, I pushed a rebase and removed all the changes... I'm so clumsy with git x). Closing for now. I'll make another PR.

**Pull request closed without merging**
