### PR TITLE
chore: update astro logo

### LINKED ISSUE #807: Docs: update Astro Logo in Installation Guide
The [Meta Framework Guide](https://qwikui.com/docs/headless/install/#meta-framework-guides) section is using an old logo for Astro and can be updated from [Astro press](https://astro.build/press/#assets)

### PR DESCRIPTION
**Pull request by at-the-vr**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests
- [ ] Other

# Why is it needed?
- keeping brand logo up to date on docs

- closes #807 
# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [ ] I have ran `pnpm change` and documented my changes
- [ ] I have add necessary docs (if needed)
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Review by adaliszk — APPROVED** [review]
LGTM

**Comment by at-the-vr** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by maiieul** [comment]
Hey @at-the-vr thanks so much for the PR.

What do you think about using the colored logo instead

image

Just a little preference on my end 🙈

**Comment by at-the-vr** [comment]
The logo is in fact colored. I have made sure of it, sharing link to a [loom recording for the changes](https://www.loom.com/share/5b28b6f74c0445fc89497c49d0fe95bf?sid=01bdd3f6-87df-48f9-9c99-fec062d4342e). Working locally 💯, could appreciate if there was a Preview Build for everyone to review it properly

**Comment by maiieul** [comment]
I added the gradient to light mode as well. I'll ask them if it's problematic.. But then I'd have to think of another way to display the two meta-frameworks logo, cause the colored qwik-city next to the black Astro feels completely off imo..

**Comment by maiieul** [comment]
Thanks again @at-the-vr 🙏

**Pull request merged**
