### PR TITLE
feat(input): add input component

### PR DESCRIPTION
**Pull request by tleperou**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

Add a wrapper to handle user inputs – aria-compliant:
- wrap in a representational div
- add label with `for`
- add input with `labeledby`
- support `hint` (cf. instructions) and `message` (cf. errors)

# Use cases and why

Anywhere user inputs are needed.

# Screenshots/Demo

n/a

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by tleperou** [comment]
I used the input-phone to integrate the doc – hence the merges.

**Question**: shall it be a Primitive?

**Review by gioboa — APPROVED** [review]
Looks good to me

**Comment by gioboa** [comment]
> I used the input-phone to integrate the doc – hence the merges.
> 
> **Question**: shall it be a Primitive?


I think the input implementation here is an headless one because it's more than just an input wrapper.

**Comment by gioboa** [comment]
Closed #257

**Pull request merged**
