### PR TITLE
docs(toc): improve code readability

### PR DESCRIPTION
**Pull request by maiieul**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests
- [ ] Other

# Why is it needed?

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have ran `pnpm change` and documented my changes
- [ ] I have add necessary docs (if needed)
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by TheMcnafaha** [comment]
Also, there's a bug that was introduced from me changing the template to match shadcn's. The h1 is no longer being rendered since it's the starting point and the recursion only adds child nodes,  so no h1.

**Comment by TheMcnafaha** [comment]
Also x2, some of the mdx doesn't have continuous heading levels. Separator is a good example, so the error is being thrown.

**Comment by maiieul** [comment]
> Also x2, some of the mdx doesn't have continuous heading levels. Separator is a good example, so the error is being thrown.

I fixed this in another PR. 

> Also, there's a bug that was introduced from me changing the template to match shadcn's. The h1 is no longer being rendered since it's the starting point and the recursion only adds child nodes, so no h1.

Can you fix this in another PR?

**Comment by TheMcnafaha** [comment]
> Can you fix this in another PR?
Sure. I'll fork this branch and ping you ind discord once i've fixed it.

**Pull request closed without merging**
