### PR TITLE
docs(colors): replace colors with css-vars for auto dark/light mode and single source of truth

### PR DESCRIPTION
**Pull request by maiieul**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

This PR is basically about changing those kind of tailwind classes:
```tsx
border-qwikui-blue-500 bg-qwikui-blue-50 dark:bg-qwikui-purple-100 dark:border-qwikui-purple-500 
```
to a "`background`/`foreground`" pair:
```tsx
border-primary text-accent-foreground
```

I had to change a bit the design to something more minimalistic because css vars create a bit more constraints.

It's a tradeoff between 

- css vars => consistency and reusability
- tailwind classes => creativity and flexibility

I think whenever there is light mode and dark mode, CSS vars win, as you don't have to define dark colors anymore. But I would probably even use them on an app with no dark mode.

Thanks to CSS vars, this PR also adds light mode for component previews -which is an important fix for fluffy.

Best way to check it out is to try it in dev.

Screenshots:
Screenshot from 2023-12-07 16-58-56
Screenshot from 2023-12-07 16-58-52
Screenshot from 2023-12-07 17-02-53
Screenshot from 2023-12-07 17-02-50
Screenshot from 2023-12-07 16-59-50
Screenshot from 2023-12-07 16-59-43
Screenshot from 2023-12-07 17-05-39
Screenshot from 2023-12-07 17-05-32
Screenshot from 2023-12-07 17-06-12
Screenshot from 2023-12-07 17-06-02

Look at how it fixes the black&white mismatch for fluffy:
Screenshot from 2023-12-07 17-07-16
Screenshot from 2023-12-07 17-06-58
Screenshot from 2023-12-07 17-06-50

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by TheMcnafaha** [comment]
Could you make the background be offwhite or a very light gray on the body? It would make our pure whites stand out better. This might be outside this particular pr, but if it could be done based in this branch/repo we would avoid a lot of merge conflicts. 

 I've attached some images below showing what I mean.

og
lightgray
darker-lightgray

**Comment by shairez** [comment]
Thanks @maiieul !

Please merge main and see if it fixes the errors

**Comment by maiieul** [comment]
Looks like the tests are passing @shairez

**Comment by maiieul** [comment]
@TheMcnafaha Thanks for the feedback! I think this can wait for another PR. This one is already too big :sweat_smile: . I'm not sure I understand why this would create merge conflicts :thinking: .

Personally, I prefer full white. We can use shadows and borders to create contrast. A lot of websites are full white.

**Comment by thejackshelton** [comment]
Merging!

**Pull request merged**
