### PR TITLE
feat(badge): add accessible attribute for badge component

### LINKED ISSUE #292: feat(badge) Make the badge more accessible
# Summary

Badges shall use by default status role and content flow DOM elements.

Such implementation helps follow the WAI ARIA and HTML practices:

```tsx
<span class="..." role="status"><Slot /></span>
```

# Concerns

* we could let integrators customise the role

### PR DESCRIPTION
**Pull request by fmgono**
fix #292

# What is it?
- Adding accessible attribute for badge component
- Adding badge component docs in headless ui
- [x] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description
Solve https://github.com/qwikifiers/qwik-ui/issues/292
Adding accessible attribute for badge component

# Use cases and why
For better accessbility
# Screenshots/Demo

image
image

The docs:
image

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by fmgono** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gioboa** [comment]
Thanks for your contribution 👍 
Can you add the documentation for this component?
here is and [example](https://github.com/qwikifiers/qwik-ui/tree/main/apps/website/src/routes/docs/headless/(components)/accordion)

**Comment by fmgono** [comment]
Sure, on it!

**Comment by thejackshelton** [comment]
Closing, kit-tailwind is now deprecated. Would be awesome if this could be moved to fluffy.

**Pull request closed without merging**
