### PR TITLE
fix(typos): minor typo correction in comments

### PR DESCRIPTION
**Pull request by uceumice**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Typos

# Description

Fixes are grammatical and involve only comments in `vite.config.ts` files.

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by uceumice** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thejackshelton** [comment]
Hey @uceumice! Appreciate the contribution 😄 . Is there a reason macroplugin was removed from the vite config?

**Comment by uceumice** [comment]
> Hey @uceumice! Appreciate the contribution 😄 . Is there a reason macroplugin was removed from the vite config?

Hey, sorry, it was an accident!

**Comment by thejackshelton** [comment]
All good. Thanks for the PR! Merging. 

Also nice to meet you @uceumice!

> Ad astra abyssosque, Traveler✨

I am a neuvillette main 💧 

We're close to releasing some pretty exciting stuff, but currently trying to fix an issue in qwik core so the library can be used before we say anything 😅 

Let me know if you got any questions regarding Qwik or Qwik UI patterns! Is there anything in particular you'd really like with Qwik UI? 

A component that doesn't require any primitives underneath is the Toggle component, and it could use some a11y and functionality improvements. Some contribution opportunities there if you're interested.

**Comment by gioboa** [comment]
@all-contributors please add @uceumice code, ideas, maintenance

**Pull request merged**
