### PR TITLE
feat(component): Add loading indicator

### PR DESCRIPTION
**Pull request by riccardo-vettore**
# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests

# Description

Add new loading indicator component

# Use cases

```html
<LoadingIndicator
      style="font-size: 3rem"
      width="10px"
      indicatorColor="darkblue"
      trackColor="lightblue"
      speed="4s"
></LoadingIndicator>
```

# Screenshots/Demo
image

### CODE REVIEW

**Comment by gioboa** [comment]
I'm thinking if loading-indicator is the right name.
I checked angular material and they call this component `spinner` https://material.angular.io/components/progress-spinner/overview
What do you think about this?

**Comment by riccardo-vettore** [comment]
Yes, I agree, this component should be called `spinner`.

**Comment by gilf** [comment]
> Yes, I agree, this component should be called `spinner`.

Agree with @gioboa. The component should be called Spinner. Once you change the name, we will merge it :)

**Comment by gioboa** [comment]
Great work. Thanks

**Comment by gioboa** [comment]
Closes #133

**Pull request merged**
