### PR TITLE
fix(website): fix initial theme usage when os is in dark mode

### PR DESCRIPTION
**Pull request by adamgen**
Add window.matchMedia as a fallback to determine light/dark theme when there's no localStorage value for theme-settings

# What is it?

- [ ] Feature / enhancement
- [+] Bug
- [ ] Docs / tests

# Description

Tiny change to fix the website header.

# Use cases and why

Described here https://github.com/qwikifiers/qwik-ui/issues/392

# Screenshots/Demo

image

# Checklist:

- [+] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [+] I have performed a self-review of my own code
- [n/a] I have made corresponding changes to the documentation
- [n/a] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by shairez** [comment]
Thanks for the fix @adamgen !

Only thing left is to write a comment following the [instructions here](https://github.com/qwikifiers/qwik-ui/pull/393#issuecomment-1680890890) 
so we can merge this PR

Thanks again!

**Comment by adamgen** [comment]
I have read the CLA Document and I hereby sign the CLA ✍️

**Comment by adamgen** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thejackshelton** [comment]
Appreciate the fix here Adam! Merging.

**Comment by shairez** [comment]
@all-contributors please add @adamgen for docs and bugs

**Pull request merged**
