### PR TITLE
fix: added name props

### PR DESCRIPTION
**Pull request by harshmangalam**
Added input name props in styled Input component

### CODE REVIEW

**Comment by harshmangalam** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by thejackshelton** [comment]
Hey @harshmangalam. Appreciate the PR! Could you not add the name property before? It looks like the props are being spread.

**Comment by thejackshelton** [comment]
Oh I see it was destructured

**Comment by thejackshelton** [comment]
LGTM! Merged 🙌

**Pull request merged**
