### PR TITLE
docs(daisy popover): replace Box component instead of Header in daisy popover demo

### PR DESCRIPTION
**Pull request by Balastrong**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

I noticed in the daily popover demo the hover one was not working. I think `Header` wasn't intended to be used there, but `Box` instead.

---

The file in this PR has a lot of changes because it wasn't formatted (probably due to #167) but the only actual changes are:

1. From this:
https://github.com/qwikifiers/qwik-ui/blob/5dd9f689f8823754eef69c277295173e0fc536d5/packages/website/src/routes/docs/daisy/popover/index.tsx#L88
to this:
https://github.com/qwikifiers/qwik-ui/blob/e8e4e33d524a1af5fec1be6a4e2ab3bfb5499084/packages/website/src/routes/docs/daisy/popover/index.tsx#L126-L128

2. The removal of these two imports:
https://github.com/qwikifiers/qwik-ui/blob/5dd9f689f8823754eef69c277295173e0fc536d5/packages/website/src/routes/docs/daisy/popover/index.tsx#L5-L6

3. A few `className` replaced with `class`.

### CODE REVIEW

**Comment by gioboa** [comment]
@Balastrong There other warnings to solve, can you fix them please?
Screenshot 2023-02-19 at 12 23 54

**Comment by Balastrong** [comment]
Sure! :)

**Comment by gioboa** [comment]
Closed #167

**Comment by Balastrong** [comment]
I fixed the rating warning and also the husky config :)


However, I'm not sure what to put in here to get rid of the `Unexpected any`  warning. What type could I use in this generic?
https://github.com/qwikifiers/qwik-ui/blob/8c5c9adafb138af995b64682e642a3fa2369a5cb/packages/headless/src/components/rating/rating.tsx#L15

**Comment by gioboa** [comment]
You can open an issue for this last question. thanks 👍

**Pull request merged**
