### PR TITLE
test(select): add story

### PR DESCRIPTION
**Pull request by naorpeled**
# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests

# Description

The select component was missing a story with a minimal test so we added it :)

# Screenshots/Demo

image

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/qwikifiers/qwik-ui/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] Added new tests to cover the fix / functionality

### CODE REVIEW

**Comment by naorpeled** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shairez** [comment]
Thanks a lot @naorpeled !

not sure what is wrong with the PNPM on CI
I'll look into it

**Comment by naorpeled** [comment]
> Thanks a lot @naorpeled !
> 
> not sure what is wrong with the PNPM on CI I'll look into it

the pnpm lock file is outdated, seems like it's like that also in main.
pushing a fix for this.

**Comment by shairez** [comment]
@all-contributors please add @naorpeled @igalklebanov for tests, code

**Pull request merged**
