### PR TITLE
build: bump qwik-nx to v0.11

### PR DESCRIPTION
**Pull request by dmitry-stepanenko**
Bumped qwik-nx to the latest version and ran migration for the project.json. Apart from the migration also updated preview target to use @nrwl/vite:preview-server executor

### CODE REVIEW

**Comment by dmitry-stepanenko** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dmitry-stepanenko** [comment]
recheck

**Comment by gioboa** [comment]
Thanks for your help @dmitry-stepanenko

**Comment by gioboa** [comment]
@all-contributors please add @dmitry-stepanenko for maintenance

**Pull request merged**
